### ISSUE TITLE
ajouter la gestion des socket par le server directement (c'est lui qui cree la cocket  et qui charge les option)

### ISSUE THREAD

**Issue by pupitoe** [pupitoe/irc_toutmeva#18]

**Comment by Shadwogg** [comment]
Par "ajouter la gestion des sockets par le serveur directement", tu veux dire, deplacer la boucle du main dans une methode boot (de la classe Server) par exemple ?

**Comment by Shadwogg** [comment]
Auss, je ne comprends pas pourquoi les fonctions dans ft_sockets.hpp, ne sont pas directement dans la classe Server (au pire, on peut creer une sous classe Socket dans le serveur, ou un attribut de type Socket aue l'on creerais pour eviter de trop surchager le code)

**Comment by pupitoe** [comment]
pour la boucle qui est dans le main autent la garder pour l'instant apres mon idee deriere la class serveur c'est qu'il possede juste les methode utile pour faire fonctionner le server, pour les fonction qui sont dans ft_socket je ne les avais pas directement mis dans le server car je n'en voyer pas l'utiliter apres si tu veux les ajouter tu peux
