### ISSUE TITLE
La classe IRCSocket n'arrive pas a etre trouve par le fichier Server.hpp | inclusion problem

### ISSUE THREAD

**Issue by Shadwogg** [pupitoe/irc_toutmeva#25]
On avait fix on rajoutant une declaration de la classe IRCSocket dans Server.hpp, mais quand je suis passe d'un pointeur a une variable alloue statiquement, cela ne fonctionne plus.

J'ai essaye de rajouter dans IRCSocket.hpp/cpp des constructeurs par copie et assignations, cela n'as rien donne.

**Comment by pupitoe** [comment]
j'ai fix le problem j'ai fait une pull request
